export const ROUTE = {
    APP: {
        ROOT: "/",
        NOT_FOUND: "*",
        ROLE: "/rt",
        LOGIN: "/login",
        SIGNUP: "/signup",
        VERIFY_OTP: "/verify-otp",
        VERIFY_EMAIL: "/verifyEmail",
        RESET_PASSWORD: "/resetPassword/:roleId",
    },
    USER: {
        HOME: "/home",
        JOBS: "/jobs",
        PROPOSALS: "/proposals",
        CONTRACTS_LIST: "/contracts/:roleType",
        PROFILE: "/profile/:type",
        PROFILE_EDIT: "/profileAlter/:type",
        PROFILE_BOOST_SUCCESS: "/profileBoostSuccess",
        WISHLIST_VIEW: "/wishlist",
        WALLET_VIEW: "/wallet",
        VIEW_JOBPOST: "/job/:jobPostId/:viewType",
        VIEW_CONTRACT: "/contract/:contractId/:roleType",
        INVITE_VIEW: "/invites",
        NOTIFIICATIONS: "/notifications/:roleId/:role",
        ALL_CHATS: "/allChats/:roleType/:roleId",
        MESSAGE_VIEW: "/chat/view/:roleType/:targetId",
    },
    CLIENT: {
        HOME: "/home",
        JOBS: "/jobs",
        VIEW_JOBPOST: "/job/:jobPostId/:viewType",
        PROPOSALS: "/proposals",
        ALL_CONTRACTS: "/contracts/:roleType",
        CONTRACT_APPROVAL: "/contractsApprovals",
        CREATE_JOBPOST: "/draftJobPost",
        VIEW_DEVELOPERS: "/developers",
        PAYMENT_SUCCESS: "/propaymentSuccess/:clientId/:dataposals",
        PAYMENT_FAILED: "/paymenFailed",
        PROFILE_VIEW: "/profile",
        VIEW_USER_PROFILE: "/userProfile/:type/:userId",
        VIEW_CONTRACT: '/contract/:contractId/:roleType"',
        VIEW_WALLET: "/wallet",
        VIEW_INVITES: "/invites",
        LIST_CHATS: "/allChats/:roleType/:roleId",
        MESSAGES: "/chat/view/:roleType/:targetId",
        NOTIFICATIONS: "/notifications/:roleId/:roles",
        PROFILE_TEST: "/profile-new",
    },
};
